-----------------------------------------------------------
---- wezterm.lua should be generated by home-manager
---- this is just an example and not guaranteed to work
-----------------------------------------------------------

-- Pull in the wezterm API
local wezterm = require("wezterm")

-- This will hold the configuration.
local config = wezterm.config_builder()

-- Spawn a fish shell in login mode
config.default_prog = { "/opt/homebrew/bin/fish", "-l" }

config.color_scheme = "N0tch2k"

local uni_font_size = 13.0
config.font_size = uni_font_size

config.font = wezterm.font_with_fallback({
	"Iosevka Term SS08 Extended",
	-- "Symbols Nerd Font", -- already bundled with wezterm
	"PingFang SC", -- MacOS only 你好
})

config.window_frame = {
	font = wezterm.font({ family = "IBM Plex Sans" }),
	font_size = uni_font_size,
}

-- other configurations, may overwrite previous ones
require("lua.core").setup(config)

-- and finally, return the configuration to wezterm
return config
